"""Interactive setup wizard for BPS Stat Agent.

Guides users through initial configuration: API keys, base URL, model selection.
Writes config files to ~/.bps-stat-agent/config/.
Auto-installs Playwright chromium if not present.
"""

import getpass
import json
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

from .config import Config


def get_user_config_dir() -> Path:
    """Return ~/.bps-stat-agent/config/."""
    return Path.home() / ".bps-stat-agent" / "config"


def needs_setup() -> bool:
    """Check if setup is needed (no config, invalid keys, or missing BPS key).

    Returns True if:
    - config.yaml not found
    - config.yaml has placeholder API key (in Config.INVALID_API_KEYS)
    - mcp.json not found or has empty BPS_API_KEY
    """
    try:
        config_path = Config.find_config_file("config.yaml")
        if not config_path:
            return True

        with open(config_path, encoding="utf-8") as f:
            data = yaml.safe_load(f)

        if not data:
            return True

        api_key = str(data.get("api_key", ""))
        if api_key in Config.INVALID_API_KEYS:
            return True

        # Check BPS API key in mcp.json
        mcp_path = Config.find_config_file("mcp.json")
        if not mcp_path:
            return True

        with open(mcp_path, encoding="utf-8") as f:
            mcp_data = json.load(f)

        bps_env = mcp_data.get("mcpServers", {}).get("bps", {}).get("env", {})
        bps_key = bps_env.get("BPS_API_KEY", "")
        if not bps_key:
            return True

        return False
    except Exception:
        return True


def _read_existing_config(config_dir: Path) -> dict:
    """Read existing config values as defaults for re-setup."""
    result = {}
    try:
        config_file = config_dir / "config.yaml"
        if config_file.exists():
            with open(config_file, encoding="utf-8") as f:
                data = yaml.safe_load(f) or {}
            api_key = str(data.get("api_key", ""))
            if api_key not in Config.INVALID_API_KEYS:
                result["ai_api_key"] = api_key
            result["ai_api_base"] = data.get("api_base", "")
            result["ai_model"] = data.get("model", "")
            result["ai_provider"] = data.get("provider", "")
    except Exception:
        pass

    try:
        mcp_file = config_dir / "mcp.json"
        if mcp_file.exists():
            with open(mcp_file, encoding="utf-8") as f:
                mcp_data = json.load(f)
            bps_key = mcp_data.get("mcpServers", {}).get("bps", {}).get("env", {}).get("BPS_API_KEY", "")
            if bps_key:
                result["bps_api_key"] = bps_key
    except Exception:
        pass

    return result


def _prompt(label: str, default: str = "", required: bool = False, masked: bool = False) -> str:
    """Interactive prompt with default value support."""
    while True:
        if masked:
            default_display = "****" if default else ""
        else:
            default_display = default

        if default_display:
            prompt_str = f"  {label} [{default_display}]: "
        else:
            prompt_str = f"  {label}: "

        try:
            if masked:
                value = getpass.getpass(prompt_str)
            else:
                value = input(prompt_str)
        except (EOFError, KeyboardInterrupt):
            print()
            return default

        value = value.strip()

        if not value and default:
            return default

        if not value and required:
            print("  ⚠️  This field is required. Please enter a value.")
            continue

        return value


CONFIG_TEMPLATE = """# BPS Stat Agent Configuration
# Generated by: bpsagent setup

api_key: "{ai_api_key}"
api_base: "{ai_api_base}"
model: "{ai_model}"
provider: "{ai_provider}"

retry:
  enabled: true
  max_retries: 5
  initial_delay: 1.0
  max_delay: 60.0
  exponential_base: 2.0

max_steps: 100
workspace_dir: "./workspace"
system_prompt_path: "system_prompt.md"

tools:
  enable_file_tools: true
  enable_bash: true
  enable_note: true
  enable_skills: true
  skills_dir: "./skills"
  enable_mcp: true
  mcp_config_path: "mcp.json"
  mcp:
    connect_timeout: 15.0
    execute_timeout: 120.0
    sse_read_timeout: 120.0

logging:
  level: "INFO"
  json_output: false

tracing:
  enabled: true
  exporter: "console"
"""


def _write_config_yaml(config_dir: Path, *, ai_api_key: str, ai_api_base: str, ai_model: str, ai_provider: str) -> Path:
    """Write config.yaml with user's settings."""
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.yaml"
    content = CONFIG_TEMPLATE.format(
        ai_api_key=ai_api_key,
        ai_api_base=ai_api_base,
        ai_model=ai_model,
        ai_provider=ai_provider,
    )
    config_path.write_text(content, encoding="utf-8")
    return config_path


def _write_mcp_json(config_dir: Path, *, bps_api_key: str) -> Path:
    """Write mcp.json with BPS API key and full research ecosystem servers.

    Includes BPS data server plus academic research MCP servers
    (paper search, citation management, PDF processing, code execution,
    knowledge graph, vector search, etc.).
    """
    config_dir.mkdir(parents=True, exist_ok=True)
    mcp_path = config_dir / "mcp.json"
    mcp_data = {
        "mcpServers": {
            "bps": {
                "description": "BPS Indonesia Statistical Data Search - AllStats Search Engine",
                "command": "bps-mcp-server",
                "args": [],
                "env": {
                    "BPS_API_KEY": bps_api_key,
                    "BPS_DEFAULT_DOMAIN": "5300",
                    "BPS_SEARCH_DELAY": "3",
                },
                "disabled": False,
            },
            "papers": {
                "description": "Academic Paper Search - 22 sources (arXiv, PubMed, Semantic Scholar, CrossRef, OpenAlex, etc.)",
                "command": "npx",
                "args": ["-y", "@openags/paper-search-mcp"],
                "env": {},
                "disabled": False,
            },
            "pdf": {
                "description": "PDF Processing - text extraction, OCR, tables, annotations, merge/split",
                "command": "uvx",
                "args": ["mcp-pdf"],
                "env": {},
                "disabled": False,
            },
            "jupyter": {
                "description": "Jupyter Code Execution - real-time notebook control, multimodal output",
                "command": "uvx",
                "args": ["jupyter-mcp-server"],
                "env": {},
                "disabled": False,
            },
            "markitdown": {
                "description": "MarkItDown (Microsoft) - Convert any file to Markdown: PDF, DOCX, PPTX, XLSX, HTML, images",
                "command": "uvx",
                "args": ["markitdown-mcp"],
                "env": {},
                "disabled": False,
            },
            "memory": {
                "description": "Knowledge Graph Memory - persistent memory system for research context",
                "command": "npx",
                "args": ["-y", "@modelcontextprotocol/server-memory"],
                "env": {},
                "disabled": False,
            },
            "zotero": {
                "description": "Zotero Citation Manager - semantic search, BibTeX export, PDF annotations",
                "command": "uvx",
                "args": ["pyzotero"],
                "env": {
                    "ZOTERO_LIBRARY_ID": "",
                    "ZOTERO_LIBRARY_TYPE": "user",
                    "ZOTERO_API_KEY": "",
                },
                "disabled": True,
            },
            "overleaf": {
                "description": "Overleaf LaTeX Editor - full CRUD, LaTeX structure, git history, PDF compile",
                "command": "npx",
                "args": ["-y", "overleaf-mcp"],
                "env": {
                    "OVERLEAF_BASE_URL": "https://www.overleaf.com",
                    "OVERLEAF_EMAIL": "",
                    "OVERLEAF_PASSWORD": "",
                },
                "disabled": True,
            },
            "qdrant": {
                "description": "Qdrant Vector Search - semantic memory for paper embeddings",
                "command": "uvx",
                "args": ["mcp-server-qdrant"],
                "env": {
                    "QDRANT_URL": "http://localhost:6333",
                    "COLLECTION_NAME": "research_papers",
                },
                "disabled": True,
            },
            "neo4j": {
                "description": "Neo4j Knowledge Graph - Cypher queries, citation network analysis",
                "command": "npx",
                "args": ["-y", "@neo4j/mcp-neo4j"],
                "env": {
                    "NEO4J_URI": "bolt://localhost:7687",
                    "NEO4J_USER": "neo4j",
                    "NEO4J_PASSWORD": "",
                },
                "disabled": True,
            },
            "chroma": {
                "description": "ChromaDB Vector Search - semantic and full-text search",
                "command": "uvx",
                "args": ["chroma-mcp"],
                "env": {},
                "disabled": False,
            },
            "pubmed": {
                "description": "PubMed Biomedical Search - PubMed, Europe PMC, CORE, OpenAlex",
                "command": "uvx",
                "args": ["pubmed-search-mcp"],
                "env": {},
                "disabled": False,
            },
            "rmcp": {
                "description": "R Statistical Computing - 52 tools, 429 R packages",
                "command": "npx",
                "args": ["-y", "rmcp"],
                "env": {},
                "disabled": False,
            },
        }
    }
    mcp_path.write_text(json.dumps(mcp_data, indent=4, ensure_ascii=False), encoding="utf-8")
    return mcp_path


def _copy_system_prompt(config_dir: Path) -> Path | None:
    """Copy system_prompt.md from package config to user config."""
    config_dir.mkdir(parents=True, exist_ok=True)
    dest = config_dir / "system_prompt.md"
    if dest.exists():
        return dest  # Don't overwrite user customizations

    source = Config.get_package_dir() / "config" / "system_prompt.md"
    if source.exists():
        shutil.copy2(source, dest)
        return dest
    return None


def _install_playwright_chromium() -> bool:
    """Install Playwright chromium browser if not present."""
    try:
        print("\n📦 Checking Playwright chromium...")
        result = subprocess.run(
            [sys.executable, "-m", "playwright", "install", "chromium"],
            capture_output=False,
            timeout=300,
        )
        if result.returncode == 0:
            print("✅ Playwright chromium ready")
            return True
        print("⚠️  Playwright install had issues (non-fatal)")
        return False
    except FileNotFoundError:
        print("⚠️  Playwright not found. Install manually: python -m playwright install chromium")
        return False
    except subprocess.TimeoutExpired:
        print("⚠️  Playwright install timed out (non-fatal)")
        return False
    except Exception as e:
        print(f"⚠️  Playwright install error: {e}")
        return False


def run_setup_wizard(force: bool = False) -> bool:
    """Run the interactive setup wizard.

    Args:
        force: If True, run even if already configured.

    Returns:
        True if setup completed successfully.
    """
    config_dir = get_user_config_dir()

    # Banner
    print("╔══════════════════════════════════════════════════╗")
    print("║       🚀 BPS Stat Agent — Setup Wizard          ║")
    print("╚══════════════════════════════════════════════════╝")
    print()

    # Load existing values as defaults
    existing = _read_existing_config(config_dir)

    if existing and not force:
        print("  ℹ️  Existing configuration found. Press Enter to keep current values.\n")

    # 1. AI Configuration
    print("━━━ AI Configuration ━━━")
    print("  Get your API key from your AI provider's dashboard.\n")

    ai_api_key = _prompt(
        "AI API Key",
        default=existing.get("ai_api_key", ""),
        required=True,
        masked=True,
    )

    ai_api_base = _prompt(
        "AI API Base URL",
        default=existing.get("ai_api_base", "") or "https://platform.minimax.io",
    )

    ai_model = _prompt(
        "AI Model",
        default=existing.get("ai_model", "") or "MiniMax-M2.5",
    )

    ai_provider = _prompt(
        "AI Provider (openai/anthropic)",
        default=existing.get("ai_provider", "") or "openai",
    )
    # Validate provider
    if ai_provider not in ("openai", "anthropic"):
        print(f"  ⚠️  Invalid provider '{ai_provider}', defaulting to 'openai'")
        ai_provider = "openai"

    # 2. BPS Configuration
    print("\n━━━ BPS Configuration ━━━")
    print("  Get your BPS API key from: https://webapi.bps.go.id")
    print("  (Free registration required)\n")

    bps_api_key = _prompt(
        "BPS API Key",
        default=existing.get("bps_api_key", ""),
        required=True,
    )

    # 3. Write config files
    print("\n━━━ Writing Configuration ━━━")

    config_path = _write_config_yaml(
        config_dir,
        ai_api_key=ai_api_key,
        ai_api_base=ai_api_base,
        ai_model=ai_model,
        ai_provider=ai_provider,
    )
    print(f"  ✅ {config_path}")

    mcp_path = _write_mcp_json(config_dir, bps_api_key=bps_api_key)
    print(f"  ✅ {mcp_path}")

    prompt_path = _copy_system_prompt(config_dir)
    if prompt_path:
        print(f"  ✅ {prompt_path}")

    # 4. Install Playwright
    _install_playwright_chromium()

    # 5. Summary
    print("\n╔══════════════════════════════════════════════════╗")
    print("║       ✅ Setup Complete!                         ║")
    print("╚══════════════════════════════════════════════════╝")
    print(f"\n  Config directory: {config_dir}")
    print(f"  AI Provider:     {ai_provider} ({ai_api_base})")
    print(f"  AI Model:        {ai_model}")
    print(f"  BPS API Key:     {'*' * 8}...{bps_api_key[-4:] if len(bps_api_key) > 4 else '****'}")
    print("\n  Run 'bpsagent' to start the agent.")
    print()

    return True
