"""Workspace scaffolding for research projects.

Creates the standard directory structure for a research project:
  data/raw/, data/processed/, data/cache/
  literature/, literature/papers/, literature/summaries/
  analysis/scripts/, analysis/results/, analysis/figures/
  writing/sections/, writing/compiled/
  review/
  checkpoints/
"""

from __future__ import annotations

from pathlib import Path

from .project_state import ProjectState

# Standard workspace directories
WORKSPACE_DIRS = [
    "data/raw",
    "data/processed",
    "data/cache",
    "literature",
    "literature/papers",
    "literature/summaries",
    "analysis/scripts",
    "analysis/results",
    "analysis/figures",
    "writing/sections",
    "writing/compiled",
    "review",
    "checkpoints",
]

# Files to create with initial content
WORKSPACE_FILES: dict[str, str] = {
    "literature/references.bib": (
        "% BibTeX bibliography for research project\n"
        "% Generated by BPS Academic Research Agent\n"
        "% Add references using citation_manager tool\n\n"
    ),
    "data/cache/.gitkeep": "",
    "literature/papers/.gitkeep": "",
    ".gitignore": (
        "# Research project gitignore\n"
        "data/cache/\n"
        "literature/papers/*.pdf\n"
        "writing/compiled/\n"
        "checkpoints/\n"
        "*.pyc\n"
        "__pycache__/\n"
    ),
}


class WorkspaceScaffolder:
    """Creates and manages research project workspace structure."""

    def __init__(self, workspace_path: str | Path) -> None:
        self.workspace_path = Path(workspace_path)

    def scaffold(self, project_state: ProjectState | None = None) -> Path:
        """Create the full workspace directory structure and initial files.

        Args:
            project_state: The project state to save

        Returns:
            Path to the workspace root
        """
        # Create directories
        for dir_path in WORKSPACE_DIRS:
            (self.workspace_path / dir_path).mkdir(parents=True, exist_ok=True)

        # Create initial files
        for file_path, content in WORKSPACE_FILES.items():
            full_path = self.workspace_path / file_path
            if not full_path.exists():
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.write_text(content, encoding="utf-8")

        # Save project state if provided
        if project_state is not None:
            project_state.save(self.workspace_path)

        return self.workspace_path

    def verify(self) -> dict[str, bool]:
        """Verify workspace structure integrity.

        Returns:
            Dict mapping directory/file paths to existence status
        """
        results = {}
        for dir_path in WORKSPACE_DIRS:
            results[dir_path] = (self.workspace_path / dir_path).is_dir()

        project_yaml = self.workspace_path / "project.yaml"
        results["project.yaml"] = project_yaml.exists()

        bib_file = self.workspace_path / "literature/references.bib"
        results["literature/references.bib"] = bib_file.exists()

        return results

    def get_workspace_summary(self) -> str:
        """Get a summary of workspace contents.

        Returns:
            Formatted summary string
        """
        lines = [f"## Workspace: {self.workspace_path.absolute()}", ""]

        for dir_path in WORKSPACE_DIRS:
            full_path = self.workspace_path / dir_path
            if full_path.exists():
                file_count = sum(1 for f in full_path.iterdir() if f.is_file() and f.name != ".gitkeep")
                lines.append(f"  📁 {dir_path}/ ({file_count} files)")
            else:
                lines.append(f"  ❌ {dir_path}/ (missing)")

        return "\n".join(lines)
